"""empty message

Revision ID: b235bd9f0140
Revises: f8cd7db34585
Create Date: 2021-11-06 14:42:24.340226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b235bd9f0140'
down_revision = 'f8cd7db34585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('professor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alunos', 'professores', ['professor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.drop_column('alunos', 'professor_id')
    # ### end Alembic commands ###
